{% set name = "coretran" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/leonfoks/{{ name }}
  git_rev: {{ version }}

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}      # [win]
    - make                       # [unix]

test:
  commands:
    - test -s $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - test -d $PREFIX/include/{{ name }}           # [unix]
    - if not exist %LIBRARY_INC%\\{{ name }} exit 1      # [win]
    - if not exist %LIBRARY_LIB%\\{{ name }}.lib exit 1  # [win]

about:
  home: https://github.com/leonfoks/coretran
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The coretran numerical library
  description: |
    Coretran is an easy to follow library to make Fortran easier in
    general with wrapped interfaces, sorting routines, kD-Trees, and
    other algorithms to handle scientific data and concepts. The
    library contains core Fortran routines and object-oriented
    classes.
  doc_url: https://leonfoks.github.io/coretran
  dev_url: https://github.com/leonfoks/coretran
