language: generic

os:
  - linux
  - osx

env:
  global:
    - CONDA_PREFIX=$HOME/conda
    - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
    - TRAVIS_PYTHON_VERSION="3.*"
    - secure: "E0qO1sU8OBS24Gw5WaYWnO8+qPj2ACvmBDF9ys8BVDmE2lR6yybn33/Yx+GkPLHqPCxAUMFY3R0TrAvHQ1eTAAuo40/J0q2XtRqbumF2sGklwU5hbbYa9qzIpJ4esjhwMWM303SoVGdrTpvbLNvAWNpRDgkxsEuqgdjd9lSyDzTBNkqComOntr3VOdUr22M0WgwUakAiPdncumaw2swoS6AZUnzNmhbDBqy+wSeg22z2Yj4wuvdCkHMP58imy54e6mLbg4cvERg+eNQucy3N0vBo8ZGzmGD1KSyw+ylFwKHn9MG0aaOd9F7A24DYwpcHkOREOSIQUm3q2rEIgY+1Pw4CCXjbsQ1PSp16lf9+FKCKaZ2S9b0WcnVlHA1Wc3X92AR+wcFXCRaNYuiSEnpbrIMPxzT+ZwzJ5uEeJARb8Jq6UgmWS/1XaXU1wo+7vtf4LpSneLPKVTJA8xE+1Gs+WuNpsILiDtqO3SlYRvLg0AGhbzWZUbf4VuZDwauuYMaM0O0qTxJz31eczi8x+l8ofYrxl4hKZxbg0qMxw4RPgXHF9QKn7uU4Dc11tit+N6sHIvx83tTKYloDL7JWyK8EjjAqgZMCUKU3eoveZlVDsHtHUJhpCZ37jyyglaR3NSY7yZo34VLxGIxCna8gTKYIU+//swrtR72xS5WJRa2QvwM="

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew remove --force $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install python=$TRAVIS_PYTHON_VERSION -c conda-forge
  - conda install -q conda-build anaconda-client -c conda-forge

script:
  - conda build ./recipe -c conda-forge --old-build-string

after_success:
  - curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
  - echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
